# Core configs
[core]
focus-on = "hover"
xdg-iteractive = true
layout-mode = "tiling"

# Setup Environment Variables
[env]
xcursor_theme = "capitaine-cursors"
xcursor_size = 24

# Eye Candy and Effects
[candy]
gap = 2
opacity = 1.0

[candy.border]
active = "#eee"
inactive = "#aaa"
thickness = 2

[candy.blur]
enabled = true
strength = 1.0
alpha = 1.0

# Keybindings
[bindings]
"Alt+Return" = ["spawn", "kitty"]
"Alt+Q" = ["close-active-window"]
"Alt+1" = ["switch-workspace", "1"]
"Alt+2" = ["switch-workspace", "2"]
"Alt+3" = ["switch-workspace", "3"]
"Alt+4" = ["switch-workspace", "4"]
"Alt+5" = ["switch-workspace", "5"]

"Alt+M" = ["toggle-monocle"]
"Alt+J" = ["cycle-monocle"]
