name: Deploy Site

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup python venv
        run: python3 -m venv venv

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r docs/requirements.txt

      - name: Build docs
        run: make -C docs html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
